
[analytics]
enabled = true

[[analytics.publishers]]
type = "moesif"
enabled = true

[analytics.publishers.settings]
application_id = "<MOESIF_APPLICATION_ID>"

[router]
gateway_host = "*"

[router.access_logs]
enabled = true

[controller.auth.basic]
enabled = true

[[controller.auth.basic.users]]
username = "admin"
password = "admin"
roles = ["admin"]

# Remove policy_configurations once the issue is resolved: https://github.com/wso2/api-platform/issues/564
[policy_configurations.ratelimit_v0]
algorithm = "fixed-window"
backend = "memory"

[policy_configurations.ratelimit_v0.memory]
max_entries = 10000
cleanup_interval = "5m"

[policy_configurations.ratelimit_v0.headers]
include_x_rate_limit = true
include_ietf = true
include_retry_after = true
